name: Docker Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                platform: [
                    "linux/amd64",
                    "linux/arm64"
                ]
                tag: [
                    v1,
                    v2,
                    v3,
                    v4,

                    v18-alpine,
                    v18-bullseye,
                    v18-slim,
                    v20-alpine,
                    v20-bullseye,
                    v20-slim,
                    v21-alpine,
                    v21-bullseye,
                    v21-slim,
                    v22-alpine,
                    v22-bullseye,
                    v22-slim,
                    v23-alpine,
                    v23-bullseye,
                    v23-slim,
                ]

        name: ${{ matrix.tag }} | ${{ matrix.platform }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install Docker buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    version: latest

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                on: [push]

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'
